@echo off
color 0a
title Dragon Batch
echo Dragon Batch
echo
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0OOkxxxxxxxkOO0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMWX0kdlc;'...              ..';lodOXWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMWX0kdl:,..                               .;lxKK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMN0xl:,..                                          .';dOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMWN0kxdl:,.                                            'oxOkddkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMWXOd:.                                        lNWWN0dc,:xXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMWKd.                                     .kMMMMMMNOl,'l0WMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMO.                                    oWMMMMMMNXXKd'.:x0KXWMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMk.                                   :XMMMMMMWXOo::;    ..,lkXMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMWO,..'..                              ,0MMMMMMMNkc.            .lONMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMKdd0XNX0c.                           .kWMMMMMWO;                  'oXMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMWNNMMMMMMk.                           lNMMMMMWk'        ..      ';..cKMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMX:       ..                   dMMMMMMNc      .l0X0lcc;. .,lOWMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMWd  .:lxO000Od,                ,0WMMMMWo       ;OWWWMMW0o:cdkk0NMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMNc.dXWMMMMMMMMNk'               .cx0NWMK:       .;xXWMMMMMMWKxkXMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMWkxWMMMMMMMMMMMMXOd.               ..;cdc.         .lKMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMO.                                 'OMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:                                   :NMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                                   ,KMMMWX0XWMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc ..''.                             :XMMNo..;xXMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0odc,.                             'OWMWO'  .;OWMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.                               'ON0d:. 'llc0MMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.                   .......       .;,..,okNMNNWMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,                  .:k0XXXXXo         .;kNMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'                    :KMMMMMWk,.     'o0WMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:       'lxO:          'kWMMMMMWXOd:. ,kNMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.     .oXMMMx.          .dWMMMMMMMMMX:  oWMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     'OWMXxdc.           .dWMMMMMMMMMKc .kNMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     .;:::.                ;XMMMMMMMMWXd. :XMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMWXNWMMMMMMMMMMMMk.    ..                    .lNMMMMMMMMWKkdxXMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMN0OXWMMMMMMMMMMMMNl    'c. .lkdlc;.    .cxxxxO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMKoxNMMMMMMMMMMMMMMk.   .kd .dWMMMMWKo'  ,xOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMWk:dWMMMMMMMMMMMMMMX;   .xO. ,KMMMMMMMMNx;.  .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMWk'lNMMMMMMMMMMMMMMNl   .xXo. cNMMMMMMMMMMWO'.,';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMK,'0MMMMMMMMMMMMMMXc   .dx: .cKMMMMMMMMMMMMM0;l0olKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMx.,KMMMMMMMMMMMMWO;   ,xo',o0WMMMMMMMMMMMMMMNOKMXOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMx..xWMMMMMMMMMNO:.  .lXNXXWMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMM0, .o0XXXKK0ko,   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMWO;  ......    .,oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMNOoc;,'',;:lx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWNWWWWNNNWWN0OKNNNWWWNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkkOkxkOOkOkx0Oc;dOOOOkkxOK0OOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo	MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXNWWWWWXNWNNWMWWWNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
pause >nul
